name: General workflow

on:
  workflow_dispatch:

jobs:

  npm-lint:
    runs-on: "ubuntu-latest"

    name: Static analysis

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14

      - name: "Install"
        run: npm install

      - name: "Lint CSS"
        run: npm run lint
